module.exports = {
  abilities: require('./build/abilities.json'),
  ability_ids: require('./build/ability_ids.json'),
  ability_keys: require('./build/ability_keys.json'),
  ancients: require('./build/ancients.json'),
  cluster: require('./build/cluster.json'),
  countries: require('./build/countries.json'),
  game_mode: require('./build/game_mode.json'),
  heroes: require('./build/heroes.json'),
  hero_abilities: require('./build/hero_abilities.json'),
  hero_names: require('./build/hero_names.json'),
  items: require('./build/items.json'),
  item_colors: require('./build/item_colors.json'),
  item_groups: require('./build/item_groups.json'),
  item_ids: require('./build/item_ids.json'),
  lobby_type: require('./build/lobby_type.json'),
  neutral_abilities: require('./build/neutral_abilities.json'),
  order_types: require('./build/order_types.json'),
  patch: require('./build/patch.json'),
  permanent_buffs: require('./build/permanent_buffs.json'),
  player_colors: require('./build/player_colors.json'),
  region: require('./build/region.json'),
  skillshots: require('./build/skillshots.json'),
  xp_level: require('./build/xp_level.json')
};